todo-aspnetcoremvc-ui/Controllers/TodoEntryController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using todo_aspnetcoremvc_ui.Infrastructure;
using todo_aspnetcoremvc_ui.Models;
using todo_aspnetcoremvc_ui.Models.ViewModels;
using todo_domain_entities.Interfaces;
using todo_domain_entities.Models;

namespace todo_aspnetcoremvc_ui.Controllers
{
    [Authorize]
    public class TodoEntryController : Controller
    {
        private readonly ITodoEntryRepository _entryRepo;
        private readonly ITodoListRepository _listRepo;
        private readonly IMapper _mapper;
        private readonly IUserProvider _userProvider;
        public TodoEntryController(ITodoEntryRepository repo, ITodoListRepository listRepo, IMapper mapper, IUserProvider userProvider = null)
        {
            _entryRepo = repo;
            _listRepo = listRepo;
            _mapper = mapper;
            _userProvider = userProvider;
        }

        public async Task<IActionResult> Index(ItemIndexViewModel model)
        {
            var todoList = _listRepo.TodoLists.FirstOrDefault(x => x.ID == model.Id);
            ItemIndexViewViewModel viewModel = new ItemIndexViewViewModel
            {
                TodoList = todoList,
                ShowDueTodayItems = model.ShowDueTodayItems,
                ShowOverDueItems = model.ShowOverDueItems,
                CurrentSort = model.SortOrder,
                DescriptionSort = string.IsNullOrEmpty(model.SortOrder) ? "desc_desc" : "",
                CreationDateSort = model.SortOrder == "cds" ? "cds_desc" : "cds",
                DueDateSort = model.SortOrder == "ds" ? "ds_desc" : "ds",
                PrioritySort = model.SortOrder == "ps" ? "ps_desc" : "ps",
                StatusSort = model.SortOrder == "ss" ? "ss_desc" : "ss",
                TodoListSort = model.SortOrder == "ts" ? "ts_desc" : "ts",
                BackUrl = model.BackUrl,
                Category = model.Category,
                ID = model.Id
            };

            if (model.Search != null)
            {
                model.PageNumber = 1;
            }
            else
            {
                model.Search = model.CurrentFilter;
            }

            viewModel.CurrentFilter = model.Search;

            var list = _entryRepo.TodoEntries.Include(x => x.TodoList)
                .Where(x => model.Category == null || x.TodoList.Category == model.Category);

            if (model.Id == null)
            {
                list = list.Where(x => x.TodoList.ApplicationUserId == _userProvider.GetUserId());
            }
            else
            {
                list = list.Where(x => x.TodoListID == model.Id);
            }

            if (model.ShowDueTodayItems)
            {
                list = list.Where(x => x.DueDate.Date == DateTime.Now.Date);
            }

            if (model.ShowOverDueItems)
            {
                list = list.Where(x => x.DueDate < DateTime.Now && x.EntryStatus != Status.Completed);
            }

            if (!string.IsNullOrEmpty(model.Search))
            {
                list = list.Where(x => x.Description.Contains(model.Search));
            }

            list = model.SortOrder switch
            {
                "desc_desc" => list.OrderByDescending(x => x.Description),
                "cds" => list.OrderBy(x => x.CreationDate),
                "cds_desc" => list.OrderByDescending(x => x.CreationDate),
                "ds" => list.OrderBy(x => x.DueDate),
                "ds_desc" => list.OrderByDescending(x => x.DueDate),
                "ps" => list.OrderBy(x => x.EntryPriority),
                "ps_desc" => list.OrderByDescending(x => x.EntryPriority),
                "ss" => list.OrderBy(x => x.EntryStatus),
                "ss_desc" => list.OrderByDescending(x => x.EntryStatus),
                "ts" => list.OrderBy(x => x.TodoList.Title),
                "ts_desc" => list.OrderByDescending(x => x.TodoList.Title),
                _ => list.OrderBy(x => x.Description),
            };

            int pageSize = 5;
            viewModel.List = await PaginatedList<TodoEntry>.CreateAsync(list.AsNoTracking(), model.PageNumber ?? 1, pageSize);
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(ItemViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("_FormPartialView", viewModel);
            }

            var entry = _mapper.Map<TodoEntry>(viewModel);
            bool successfull = await _entryRepo.CreateTodoEntryAsync(entry);
            
            if (!successfull)
            {
                return BadRequest("Could not create item");
            }

            if (!string.IsNullOrEmpty(viewModel.ReturnUrl))
            {
                return Redirect(viewModel.ReturnUrl);
            }

            return RedirectToAction("Index");
        }

        public IActionResult Update(int? id, string returnUrl)
        {
            if (id != null)
            {
                var todoEntry = _entryRepo.TodoEntries.FirstOrDefault(x => x.ID == id);
                if (todoEntry != null)
                {
                    ItemViewModel viewModel = _mapper.Map<ItemViewModel>(todoEntry);
                    viewModel.ReturnUrl = returnUrl;
                    return View(viewModel);
                }
            }

            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(ItemViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            var todoEntry = _entryRepo.TodoEntries.FirstOrDefault(x => x.ID == viewModel.ID);
            todoEntry = _mapper.Map(viewModel, todoEntry);
            var successfull = await _entryRepo.UpdateTodoEntryAsync(todoEntry);
            if (!successfull)
            {
                return BadRequest("Could not change item");
            }

            if (!string.IsNullOrEmpty(viewModel.ReturnUrl))
            {
                return Redirect(viewModel.ReturnUrl);
            }

            return RedirectToAction("Index"); 
        }

        public async Task<IActionResult> Delete(int? id, string returnUrl, int count)
        {
            if (id != null)
            {
                var entry = _entryRepo.TodoEntries.FirstOrDefault(x => x.ID == id);
                if (entry != null)
                {
                    var successfull = await _entryRepo.DeleteTodoEntryAsync(id.Value);
                    if (!successfull)
                    {
                        return BadRequest("Could not remove item");
                    }

                    if (!string.IsNullOrEmpty(returnUrl))
                    {
                        if (count > 1)
                        {
                            return Redirect(returnUrl);
                        }

                        int index = returnUrl.IndexOf('?');
                        string queryString = returnUrl[(index + 1)..];
                        var query = HttpUtility.ParseQueryString(queryString);
                        query.Remove("pageNumber");
                        string newQueryString = query.ToString();
                        string url = returnUrl.Substring(0, index + 1);
                        return Redirect($"{url}{newQueryString}");
                    }

                    return RedirectToAction("Index");
                }
            }

            return NotFound();
        }
    }
}

todo-aspnetcoremvc-ui/Controllers/TodoListController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using todo_aspnetcoremvc_ui.Models;
using todo_aspnetcoremvc_ui.Infrastructure;
using todo_aspnetcoremvc_ui.Models.ViewModels;
using todo_domain_entities.Models;
using todo_domain_entities.Interfaces;
using AutoMapper;

namespace todo_aspnetcoremvc_ui.Controllers
{
    [Authorize]
    public class TodoListController : Controller
    {
        private readonly ITodoListRepository _repo;
        private readonly ITodoEntryRepository _entryRepo;
        private readonly IUserProvider _userProvider;
        private readonly IMapper _mapper;
        public TodoListController(ITodoListRepository repo, IUserProvider userProvider, ITodoEntryRepository entryRepo, IMapper mapper)
        {
            _repo = repo;
            _userProvider = userProvider;
            _entryRepo = entryRepo;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index(ListIndexViewModel model)
        {
            var queryEntries = _repo.TodoLists
                .Include(x => x.TodoEntries)
                .Where(x => model.Category == null || x.Category == model.Category)
                .Where(x => x.ApplicationUserId == _userProvider.GetUserId())
                .SelectMany(x => x.TodoEntries);

            ListIndexViewViewModel viewModel = new ListIndexViewViewModel
            {
                CurrentSort = model.SortOrder,
                TitleSort = string.IsNullOrEmpty(model.SortOrder) ? "title_desc" : "",
                CategorySort = model.SortOrder == "cs" ? "cs_desc" : "cs",
                StatusSort = model.SortOrder == "ss" ? "ss_desc" : "ss",
                PrioritySort = model.SortOrder == "ps" ? "ps_desc" : "ps",
                Filter = model.Search,
                ShowHiddenLists = model.ShowHiddenLists,
                Category = model.Category,
                HideCompletedLists = model.HideCompletedLists,
                TotalEntries = queryEntries.Count(),
                DueTodayItemsCount = queryEntries.Where(x => x.DueDate.Day == DateTime.Now.Day).Count(),
                OverDueItemsCount = queryEntries.Where(x => x.DueDate < DateTime.Now && x.EntryStatus != Status.Completed).Count()
            };

            if (model.Search != null)
            {
                model.PageNumber = 1;
            }
            else
            {
                model.Search = model.CurrentFilter;
            }

            viewModel.CurrentFilter = model.Search;
            string userId = _userProvider.GetUserId();
            var list = _repo.TodoLists.Where(x => model.Category == null || x.Category == model.Category)
                .Where(x => x.ApplicationUserId == userId);

            if (!model.ShowHiddenLists)
            {
                list = list.Where(x => x.IsHidden != true);
            }

            if (model.HideListID != null)
            {
                var listToChangeVisibility = _repo.TodoLists.FirstOrDefault(x => x.ID == model.HideListID);
                if (listToChangeVisibility != null)
                {
                    listToChangeVisibility.IsHidden = !listToChangeVisibility.IsHidden;
                    bool successfull = await _repo.UpdateTodoListAsync(listToChangeVisibility);
                    if (!successfull)
                    {
                        return BadRequest("Could not change visibility");
                    }
                }
            }

            if (model.HideCompletedLists)
            {
                list = list.Where(x => x.TodoListStatus != Status.Completed);

            }

            if (!string.IsNullOrEmpty(model.Search))
            {
                list = list.Where(x => x.Category.Contains(model.Search) || x.Title.Contains(model.Search));
            }

            list = model.SortOrder switch
            {
                "title_desc" => list.OrderByDescending(x => x.Title),
                "cs" => list.OrderBy(x => x.Category),
                "cs_desc" => list.OrderByDescending(x => x.Category),
                "ss" => list.OrderBy(x => x.TodoListStatus),
                "ss_desc" => list.OrderByDescending(x => x.TodoListStatus),
                "ps" => list.OrderBy(x => x.TodoListPriority),
                "ps_desc" => list.OrderByDescending(x => x.TodoListPriority),
                _ => list.OrderBy(x => x.Title),
            };

            int pageSize = 5;

            viewModel.List = await PaginatedList<TodoList>.CreateAsync(list.AsNoTracking(), model.PageNumber ?? 1, pageSize);

            return View(viewModel);
        }

        public async Task<IActionResult> Copy(int id, string category)
        {
            var list = _repo.TodoLists.Include(x => x.TodoEntries).FirstOrDefault(x => x.ID == id);

            if (list != null)
            {
                var newList = new TodoList()
                {
                    ApplicationUserId = list.ApplicationUserId,
                    Category = list.Category,
                    Title = list.Title,
                    TodoListPriority = list.TodoListPriority,
                    TodoListStatus = list.TodoListStatus,
                };

                bool successfull = await _repo.CreateTodoListAsync(newList);
                if (!successfull)
                {
                    return BadRequest("Could not create copy");
                }

                if (list.TodoEntries.Count != 0)
                {
                    var newAddedList = _repo.TodoLists.Include(x => x.TodoEntries).OrderBy(x => x.ID).Last();
                    for (int i = 0; i < list.TodoEntries.Count; i++)
                    {
                        var entry = new TodoEntry
                        {
                            CreationDate = list.TodoEntries[i].CreationDate,
                            DueDate = list.TodoEntries[i].DueDate,
                            Description = list.TodoEntries[i].Description,
                            EntryPriority = list.TodoEntries[i].EntryPriority,
                            EntryStatus = list.TodoEntries[i].EntryStatus,
                            TodoListID = newAddedList.ID
                        };
                        bool successfullCreateEntry = await _entryRepo.CreateTodoEntryAsync(entry);
                        if (!successfullCreateEntry)
                        {
                            return BadRequest("Could not create copy");
                        }
                    }
                }

                if (!string.IsNullOrEmpty(category))
                {
                    if (_repo.TodoLists.Where(x => x.Category == category).FirstOrDefault() != null)
                    {
                        return RedirectToAction("Index", new { category = category });
                    }
                }

                return RedirectToAction("Index");
            }

            return NotFound();
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(TodoList list)
        {
            if (ModelState.IsValid)
            {
                string userId = _userProvider.GetUserId();
                list.ApplicationUserId = userId;
                bool successfull = await _repo.CreateTodoListAsync(list);
                if (!successfull)
                {
                    return BadRequest("Could not create new todo list");
                }

                return RedirectToAction("Index");
            }

            return View(list);
        }

        public async Task<IActionResult> Delete(int? id, string category)
        {
            if (id == null)
            {
                return NotFound();
            }

            var successfull = await _repo.DeleteTodoListAsync(id.Value);

            if (!successfull)
            {
                return BadRequest("Could not remove todo list");
            }

            if (!string.IsNullOrEmpty(category))
            {
                if (_repo.TodoLists.Where(x => x.Category == category).FirstOrDefault() != null)
                {
                    return RedirectToAction("Index", new { category = category });
                }         
            }

            return RedirectToAction("Index");
        }

        public IActionResult Update(int? id, string returnUrl)
        {
            if (id != null)
            {

                var todoList = _repo.TodoLists.FirstOrDefault(x => x.ID == id);

                if (todoList != null)
                {
                    var listUpdateViewModel = _mapper.Map<ListUpdateViewModel>(todoList);
                    listUpdateViewModel.ReturnUrl = returnUrl;

                    return View(listUpdateViewModel);
                }
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Update(ListUpdateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var todoList = _repo.TodoLists.FirstOrDefault(x => x.ID == viewModel.ID);
                todoList = _mapper.Map(viewModel, todoList);
                todoList.ApplicationUserId = _userProvider.GetUserId();
                bool successfull = await _repo.UpdateTodoListAsync(todoList);
                if (!successfull)
                {
                    return BadRequest("Could not update todo list");
                }

                if (_repo.TodoLists.Where(x => x.Category == viewModel.ReturnUrl).FirstOrDefault() != null)
                {
                    return RedirectToAction("Index", new { category = viewModel.ReturnUrl });
                }

                return RedirectToAction("Index");
            }

            return View(viewModel);
        }
    }
}

todo-aspnetcoremvc-ui/Views/TodoEntry/Index.cshtml
@{
    ViewData["Title"] = "Entries";
}

@model ItemIndexViewViewModel


@if (Model.TodoList != null)
{
    <h4 class="bg-primary text-white text-center p-2">To do list</h4>
    <div class="table-responsive-sm">
        <table class="table table-sm table-borderless table-responsive-sm">
            <thead>
                <tr>
                    <th style="display:none;"></th>
                    <th>Title</th>
                    <th>Priority</th>
                    <th>Status</th>
                    <th>Category</th>
                    <th class="border-0"></th>
                    <th class="border-0"></th>
                    <th class="border-0"></th>
                </tr>
            </thead>
            <tbody>
                <tr class="bg-white text-info" onchange="changeButtonsVisibility(event)">
                    <td id="todoListId" style="display:none;" class="border-bottom border-left">@Model.TodoList.ID</td>
                    <td><textarea asp-for="@Model.TodoList.Title" rows="2" class="bg-transparent border-0 text-info"></textarea></td>
                    <td>
                        <select asp-items="Html.GetEnumSelectList<Priority>()" class="bg-transparent text-info border-0" asp-for="@Model.TodoList.TodoListPriority">
                        </select>
                    </td>
                    <td>
                        <select asp-items="Html.GetEnumSelectList<Status>()" class="bg-transparent text-info border-0" asp-for="@Model.TodoList.TodoListStatus">
                        </select>
                    </td>
                    <td><input type="text" value="@Model.TodoList.Category" class="bg-transparent border-0 text-info" /></td>
                    <td class="bg-white">
                        <a id="save" class="btn btn-outline-info btn-sm text-info" style="display:none" onclick="saveChanges(event)">Save</a>
                    </td>
                    <td class="bg-white">
                        <a id="cancel" class="btn btn-outline-info btn-sm text-info" style="display:none" onclick="cancelChanges()">Cancel</a>
                    </td>
                    <td class="bg-white">
                        <a asp-action="Delete" asp-controller="TodoList" class="btn btn-outline-info btn-sm text-info" asp-route-id="@Model.TodoList.ID">Delete</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
}

@if (Model.ShowDueTodayItems)
{
    <h4 class="bg-primary text-white text-center p-2">Due today entries</h4>
}
else if (Model.ShowOverDueItems)
{
    <h4 class="bg-primary text-white text-center p-2">Overdue entries</h4>
}
else
{
    <h4 class="bg-primary text-white text-center p-2">Entries</h4>
}
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find entry: <input type="text" name="Search" value="@Model.CurrentFilter" />
            <input type="hidden" asp-for="@Model.TodoList.Category" />
            <input type="hidden" asp-for="@Model.ID" />
            <input type="hidden" asp-for="@Model.BackUrl" />
            <input type="hidden" asp-for="@Model.Category" />
            <input type="hidden"  asp-for="@Model.ShowDueTodayItems" />
            <input type="hidden" asp-for="@Model.ShowOverDueItems" />
            <input type="submit" value="Search" class="btn btn-info" />
        </p>
    </div>
</form>

@if (Model.List.Count == 0)
{
    <p class="text-center p-2 m-3">There are no entries in this list</p>
}
else
{
    var parms = new Dictionary<string, string>()
    {
        { "currentFilter", Model.CurrentFilter },
        { "backUrl", Model.BackUrl },
        { "showDueTodayItems", Model.ShowDueTodayItems.ToString() },
        { "showOverDueItems", Model.ShowOverDueItems.ToString() },
        { "id", Model.ID.ToString() },
        { "category", Model.Category }
    };

    <div class="table-responsive-sm">
        <table class="table table-sm table-borderless">
            <thead>
                <tr>
                    <th style="display:none"></th>
                    <th><a asp-action="Index" asp-all-route-data="parms" asp-route-sortOrder="@Model.DescriptionSort">Description</a></th>
                    <th><a asp-action="Index" asp-all-route-data="parms" asp-route-sortOrder="@Model.CreationDateSort">Creation date</a></th>
                    <th><a asp-action="Index" asp-all-route-data="parms" asp-route-sortOrder="@Model.DueDateSort">Duedate</a></th>
                    <th><a asp-action="Index" asp-all-route-data="parms" asp-route-sortOrder="@Model.PrioritySort">Priority</a></th>
                    <th><a asp-action="Index" asp-all-route-data="parms" asp-route-sortOrder="@Model.StatusSort">Status</a></th>
                    @if (Model.TodoList == null)
                    {
                        <th><a asp-action="Index" asp-all-route-data="parms" asp-route-sortOrder="@Model.TodoListSort">List</a></th>
                    }
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
           @foreach (TodoEntry l in Model.List)
            {
                var btnClass = l.DueDate < DateTime.Now && l.EntryStatus != Status.Completed ? "btn-outline-danger" : l.EntryStatus == Status.Completed ? "btn-outline-success" : "btn-outline-info";
                var trClass = l.DueDate < DateTime.Now && l.EntryStatus != Status.Completed ? "bg-danger" : l.EntryStatus == Status.Completed ? "bg-success" : "bg-info";
                    <tr class="@trClass text-white">
                        <td class="border-bottom border-left" style="display:none;">@l.ID</td>
                        <td class="border-bottom border-left">@l.Description</td>
                        <td class="border-bottom border-left">@l.CreationDate.ToString("dd-MM-yyyy HH:mm:ss")</td>
                        <td class="border-bottom border-left">@l.DueDate.ToString("dd-MM-yyyy HH:mm:ss")</td>
                        <td class="border-bottom border-left">@l.EntryPriority</td>
                        <td class="border-bottom border-left">@(l.EntryStatus.GetAttribute<DisplayAttribute>().Name)</td>
                        @if (Model.TodoList == null)
                        {
                            <td class="border-bottom border-left">@l.TodoList.Title</td>
                        }

                        <td class="border-0 border-bottom-0 bg-white">
                            <a asp-action="Update" class="btn @btnClass" asp-route-id="@l.ID" asp-route-returnUrl="@(Context.Request.Path + Context.Request.QueryString)">Edit</a>
                        </td>
                        <td class="border-0 bg-white border-bottom-0">
                            <a asp-action="Delete" class="btn @btnClass" asp-route-id="@l.ID" asp-route-returnUrl="@(Context.Request.Path + Context.Request.QueryString)" asp-route-count="@Model.List.Count()">Delete</a>
                        </td>
                    </tr>
            }
            </tbody>
        </table>
    </div>

    var prevDisabled = !Model.List.HasPreviousePage ? "disabled" : "";
    var nextDisabled = !Model.List.HasNextPage ? "disabled" : "";

    <a asp-action="Index"
       asp-route-sortOrder="@Model.CurrentSort"
       asp-route-pageNumber="@(Model.List.PageIndex - 1)"
       asp-route-currentFilter="@Model.CurrentFilter"
       asp-route-backUrl="@Model.BackUrl"
       asp-route-showDueTodayItems="@Model.ShowDueTodayItems"
       asp-route-showOverDueItems="@Model.ShowOverDueItems"
       asp-route-id="@Model.ID"
       asp-route-category="@Model.Category"
       class="btn btn-info @prevDisabled">
        Previous
    </a>
    <a asp-action="Index"
       asp-route-sortOrder="@Model.CurrentSort"
       asp-route-pageNumber="@(Model.List.PageIndex + 1)"
       asp-route-currentFilter="@Model.CurrentFilter"
       asp-route-backUrl="@Model.BackUrl"
       asp-route-showDueTodayItems="@Model.ShowDueTodayItems"
       asp-route-showOverDueItems="@Model.ShowOverDueItems"
       asp-route-id="@Model.ID"
       asp-route-category="@Model.Category"
       class="btn btn-info @nextDisabled">
        Next
    </a>
}

@if (Model.TodoList != null)
{
    <button class="btn bg-info float-right" style="width:100px;" onclick="changeFormVisibility()">Add</button>
    <div id="formEntry" style="display:none; margin-top:100px;" class="container-fluid">
        <partial name="_FormPartialView" model="@(new ItemViewModel()
            { TodoListID = Model.TodoList.ID,
              CreationDate = DateTime.Now,
              DueDate = DateTime.Now.AddDays(1),
              ReturnUrl = Context.Request.Path + Context.Request.QueryString
            })" />
    </div>
}

@if (!string.IsNullOrEmpty(Model.BackUrl))
{
<div class="mt-3">
    <a href="@Model.BackUrl" class="btn btn-outline-dark"><img src="~/img/back icon.png" /></a>
</div>
}

<script>

    function changeButtonsVisibility(event) {

        let tr = event.currentTarget;
        alert(tr);
        save = tr.cells[5].lastElementChild;
        cancel = tr.cells[6].lastElementChild;
        if (save.style.display === "none") {
            save.style.display = "block";
            cancel.style.display = "block";
        }
    }

    function saveChanges(event) {
        let elem = event.target;
        let parent = elem.parentElement;
        let tr = parent.parentElement;
        let id = tr.cells[0].innerText;
        let title = tr.cells[1].lastElementChild.value;
        let priority = tr.cells[2].lastElementChild.value;
        let status = tr.cells[3].lastElementChild.value;
        let category = tr.cells[4].lastElementChild.value;
        const XHR = new XMLHttpRequest();
        const FD = new FormData();
        FD.append("ID", id);
        FD.append("Title", title);
        FD.append("TodoListPriority", priority);
        FD.append("TodoListStatus", status);
        FD.append("Category", category);
        FD.append("ReturnUrl", null);

        XHR.addEventListener('load', (event) => {
            alert('Yeah! Data sent and response loaded.');
            location.reload();
        });

        XHR.addEventListener('error', (event) => {
            alert('Oops! Something went wrong.');
        });

        XHR.open("POST", "/TodoList/Update");

        XHR.send(FD);
    }

    function cancelChanges() {
        location.reload();
    }

    function changeFormVisibility() {
        let form = document.getElementById("formEntry");
        if (form.style.display === "none") {
            form.style.display = "block";
        }
        else {
            form.style.display = "none";
        }
    }
</script>

todo-aspnetcoremvc-ui/Views/TodoEntry/Update.cshtml
@model ItemViewModel
<form asp-action="Update" asp-controller="TodoEntry" method="post" class="row" style="border:1px solid skyblue">
    <div class="form-group col-xs-3 col-md-5">
        <div><span asp-validation-for="@Model.Description" class="text-danger"></span></div>
        <label asp-for="@Model.Description">Description</label>
        <textarea class="form-control" asp-for="@Model.Description"></textarea>
    </div>
    <div class="form-group col-xs-3 col-md-3" hidden>
        <label asp-for="CreationDate">CreationDate</label>
        <input type="datetime-local" class="form-control" asp-for="CreationDate" />
    </div>
    <div class="form-group col-xs-3 col-md-3">

        <div><span asp-validation-for="@Model.DueDate" class="text-danger"></span></div>
        <label asp-for="@Model.DueDate">Due date</label>
        <input type="datetime-local" class="form-control" asp-for="@Model.DueDate" />
    </div>
    <div class="form-group col-xs-3 col-md-3">
        <label for="@Model.EntryPriority">Priority</label>
        <select asp-items="Html.GetEnumSelectList<Priority>()" asp-for="@Model.EntryPriority" class="form-control">
        </select>
    </div>
    <div class="form-group col-xs-3 col-md-3">
        <label for="@Model.EntryStatus">Status</label>
        <select asp-items="Html.GetEnumSelectList<Status>()" asp-for="@Model.EntryStatus" class="form-control">
        </select>
    </div>
    <input type="hidden" asp-for="@Model.TodoListID" value="@Model.TodoListID" />
    <input type="hidden" asp-for="@Model.ReturnUrl" />
    <div class=" align-items-center d-flex">
        <button type="submit" class="btn btn-primary m-1">Submit</button>
    </div>
</form>